[manifest]
version = "0.0.1"
dump_lua = true
priority = 214748365

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_objects/blind.lua"]'''
pattern = '''SMODS.add_boss_to_used_table(ret_boss, blind_type or 'boss')'''
position = "at"
match_indent = true
payload = '''
--last minute override check to avoid index crash
local new_type = blind_type
if G.P_BLINDS[ret_boss].boss and not G.P_BLINDS[ret_boss][new_type] then
    new_type = 'boss'
    print("EMERGENCY OVERRIDE TYPE TO BOSS")
elseif G.P_BLINDS[ret_boss].big and not G.P_BLINDS[ret_boss][new_type] then
    new_type = 'big'
    print("EMERGENCY OVERRIDE TYPE TO BIG")
elseif G.P_BLINDS[ret_boss].small and not G.P_BLINDS[ret_boss][new_type] then
    new_type = 'small'
    print("EMERGENCY OVERRIDE TYPE TO SMALL")
end
SMODS.add_boss_to_used_table(ret_boss, new_type or 'boss')
'''

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_objects/blind.lua"]'''
pattern = '''ret_boss = SMODS.poll_object({type = 'Blind', blind_type = blind_type, seed = blind_type or 'boss'})'''
position = "before"
match_indent = true
payload = '''
--print("tuype incoming" .. (blind_type or 'NIL'))

'''

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils/weights.lua"]'''
pattern = '''if eligible_bosses[k] > min_use and not G.P_BLINDS[k][blind_type].allow_duplicates then'''
position = "at"
match_indent = true
payload = '''if type(eligible_bosses[k]) ~= 'boolean' and eligible_bosses[k] > min_use and not G.P_BLINDS[k][blind_type].allow_duplicates then '''

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_objects/blind.lua"]'''
pattern = '''ret_boss = pseudorandom_element(SMODS.create_blind_pool(blind_type), pseudoseed(blind_type or 'boss'))'''
position = "before"
match_indent = true
payload = '''
print("tuype incoming2--" .. (blind_type or 'NIL'))

'''


[[patches]]
[patches.regex]
target = '''=[SMODS _ "src/game_objects/blind.lua"]'''
pattern = '''string\.lower\(k\)'''
position = "at"
match_indent = true
payload = '''UNIK.check_and_change_blind_type(string.lower(k))'''

## SMODS YOU BROKE THE MUSIC
[[patches]]
[patches.pattern]
target = '''blind.lua'''
pattern = '''self[self.current_slot or ''] = nil
        local current_type = string.lower(G.GAME.blind_on_deck or '')
        self[current_type] = blind and true or nil
        self.current_slot = current_type'''
position = "at"
payload = '''
self.boss = blind and blind.boss
if not blind or (blind and not blind.boss) then
    self[self.current_slot or ''] = nil
            local current_type = string.lower(G.GAME.blind_on_deck or '')
            self[current_type] = blind and true or nil
            self.current_slot = current_type
    --print("TYUPE:" .. current_type)
    if blind and not blind.boss then 
        self.boss = nil 
        --print("deboss")
    end
end
--print(self:get_type())
--print(self.dollars)
if G.GAME.modifiers.no_blind_reward and G.GAME.modifiers.no_blind_reward[self:get_type()] then 
    self.dollars = 0 
else
    self.dollars = blind and blind.dollars or 0
end
'''
match_indent = true

## SMODS YOU BROKE THE MUSIC
[[patches]]
[patches.pattern]
target = '''blind.lua'''
pattern = '''if G.GAME.modifiers.no_blind_reward and G.GAME.modifiers.no_blind_reward[self:get_type()] then self.dollars = 0 end'''
position = "at"
payload = '''if G.GAME.modifiers.no_blind_reward and G.GAME.modifiers.no_blind_reward[self:get_type()] then 
--print("SET ZERO2!")
self.dollars = 0 
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_objects/blind.lua"]'''
pattern = '''if G.GAME.blind and self == G.GAME.blind then
        return G.GAME.blind_on_deck
    end'''
position = "at"
payload = '''
--FUCK OFF
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_objects/blind.lua"]'''
pattern = '''else return '' end'''
position = "at"
payload = '''
else
    if G.GAME.blind and self == G.GAME.blind then
        return G.GAME.blind_on_deck
    end
    return ''
end
'''
match_indent = true

##ui 
[[patches]]
[patches.pattern]
target = '''functions/UI_definitions.lua'''
pattern = '''if G.GAME.modifiers.no_blind_reward and G.GAME.modifiers.no_blind_reward[type] then _reward = nil end'''
position = "at"
payload = '''
local isSmall = G.P_BLINDS[G.GAME.round_resets.blind_choices[type]].small or false
local isBig = G.P_BLINDS[G.GAME.round_resets.blind_choices[type]].big or false
local isBoss = G.P_BLINDS[G.GAME.round_resets.blind_choices[type]].boss or false
if isSmall and G.GAME.modifiers.no_blind_reward and G.GAME.modifiers.no_blind_reward['Small'] then _reward = nil end
if isBig and G.GAME.modifiers.no_blind_reward and G.GAME.modifiers.no_blind_reward['Big'] then _reward = nil end
if isBoss and G.GAME.modifiers.no_blind_reward and G.GAME.modifiers.no_blind_reward['Boss'] then _reward = nil end
'''
match_indent = true