[manifest]
version = "0.0.1"
dump_lua = true
priority = 99999

### Rn, blindside's card drawing shennanigans is breaking smod's existing one, 

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''if (area.config.type == 'joker' or area.config.type == 'hand' and not (G.GAME.selected_back.effect.center.config.extra and G.GAME.selected_back.effect.center.config.extra.blindside) ) and not area.config.fixed_limit then'''
position = "at"
payload = '''
    if (area.config.type == 'joker' or area.config.type == 'hand') and not area.config.fixed_limit then
'''
match_indent = true

##reshuffling and tech blind stuff
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''elseif G.STATE == G.STATES.SELECTING_HAND and #G.deck.cards > 0 and self.config.card_limits.old_slots < self.config.card_limits.total_slots then'''
position = "before"
payload = '''
elseif UNIK.hasBlindside() and G.STATE == G.STATES.SELECTING_HAND and #G.deck.cards <= 0  and self.config.card_limits.old_slots < self.config.card_limits.total_slots then
    if (self.config.card_limits.total_slots - self.config.card_limits.old_slots) > 0 then
        UNIK.reshuffle()
    end
'''
match_indent = true

##moving over!
[[patches]]
[patches.pattern]
target = '''=[SMODS Blindside "lib/utils/utils.lua"]'''
pattern = '''if not BLINDSIDE.tech_temp then
        G.E_MANAGER:add_event(Event({
            func = function()
                if G.GAME.tech_draw_primary_buffer and G.GAME.tech_draw_primary_buffer > 0 then
                    BLINDSIDE.tech_temp = true
                    G.FUNCS.blind_draw_from_deck_to_hand(math.floor(G.GAME.tech_draw_primary_buffer))
                    BLINDSIDE.tech_temp = nil
                    G.GAME.tech_draw_primary_buffer = G.GAME.tech_draw_buffer
                    G.GAME.tech_draw_buffer = 0
                elseif G.GAME.tech_draw_buffer and G.GAME.tech_draw_buffer > 0 then
                    
                end
               return true
            end
        }))

        G.E_MANAGER:add_event(Event({
            func = function()
                G.E_MANAGER:add_event(Event({
                    func = function()
                        if not G.GAME.tech_draw_primary_buffer then
                            G.GAME.tech_draw_primary_buffer = 0
                        end
                        G.GAME.tech_draw_primary_buffer = G.GAME.tech_draw_primary_buffer + (G.GAME.tech_draw_buffer or 0)
                        G.GAME.tech_draw_buffer = 0
                        return true
                    end
                }))
                return true
            end
        }))
    end'''
position = "at"
payload = '''
--HASOWNDEDICATEDFUNCTION NOW
'''
match_indent = true

##crash fix
[[patches]]
[patches.regex]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''and self.config.card_limits.old_slots'''
position = "before"
payload = ''' and self.config.card_limits and self.config.card_limits.old_slots '''
match_indent = true

##reshuffling and tech blind stuff
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''if self == G.hand then check_for_unlock({type = 'min_hand_size'}) end'''
position = "after"
payload = '''
if G.hand and self == G.hand and (self.config.card_count or 0) + (SMODS.cards_to_draw or 0) >= (self.config.card_limits.total_slots or 0) then
    if UNIK.hasBlindside() and G.STATE == G.STATES.SELECTING_HAND and #G.deck.cards > 0 then
        if self.config.card_limits and self.config.card_limits.old_slots and (self.config.card_limits.total_slots - self.config.card_limits.old_slots) <= 0 then
           -- print("techdraw1")
            --print(G.GAME.can_draw_tech)
            UNIK.tech_draw()
        end
    --tech blinds btw cannot reshuffle the deck
    end
end
'''
match_indent = true


