[manifest]
version = "0.0.1"
dump_lua = true
priority = 99999

[[patches]]
[patches.regex]
target = '=[SMODS Blindside "lib/utils/utils.lua"]'
pattern = '''(.*)function BLINDSIDE.chipsupdate(.*)'''
match_indent = true
position = 'after'
payload = '''

G.GAME.unik_current_operator = G.GAME.unik_current_operator or 0

'''

[[patches]]
[patches.regex]
target = '=[SMODS Blindside "lib/utils/utils.lua"]'
pattern = '''G.GAME.blind.basechips\*G.GAME.blind.mult'''
match_indent = true
position = 'at'
payload = ''' UNIK.arrowfunction(G.GAME.unik_current_operator,G.GAME.blind.basechips,G.GAME.blind.mult) '''

[[patches]]
[patches.regex]
target = '=[SMODS _ "src/ui.lua"]'
pattern = '''text = \"X\"'''
match_indent = true
position = 'after'
payload = ''', id = "unik_operator_text_7777" '''

# the trench reset
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''
-- TARGET: effects after end of round evaluation
'''
match_indent = true
position = 'after'
payload = '''
if BLINDSIDE then
    for i, card in pairs(G.playing_cards) do
        if card.ability and card.ability.extra and card.ability.extra.e_chips and card.config.center.key == 'm_unik_blindside_epic_trench' then
            card.ability.extra.e_chips = card.ability.extra.e_chips_base
        end
        card.ability.unik_burned_by_hook = nil
    end
end
'''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "lib/utils/utils.lua"]'
pattern = '''-- TARGET: card destroyed'''
match_indent = true
position = 'after'
payload = '''

'''
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''table.insert(cards, _cards[i])'''
match_indent = true
position = 'after'
payload = '''
if _cards[i].unik_burned_by_hook then
    _cards[i].unik_burned_by_hook = nil
    burned = true
end
'''

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''table.insert(cards, _retained_cards[i])'''
match_indent = true
position = 'after'
payload = '''
if _retained_cards[i].unik_burned_by_hook then
    _retained_cards[i].unik_burned_by_hook = nil
    burned = true
end
'''

[[patches]]
[patches.regex]
target = 'functions/state_events.lua'
pattern = '''SMODS.calculate_context\(\{(.*)end_of_round = true(.*)game_over = game_over(.*)'''
match_indent = true
position = 'after'
payload = '''

G.GAME.last_joker = G.GAME.blind.boss

'''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "lib/utils/uishop.lua"]'
pattern = '''local final_free = G.GAME.current_round.free_rerolls > 0'''
match_indent = true
position = 'after'
payload = '''

--print("current Free Rerolls: ".. G.GAME.current_round.free_rerolls)
--print("overall Free Rerolls: "..  G.GAME.round_resets.free_rerolls)
'''

[[patches]]
[patches.regex]
target = 'functions/button_callbacks.lua'
pattern = '''(.*)SMODS.calculate_context\(\{(.*)ending_shop = true(.*)\}\)(.*)'''
match_indent = true
position = 'after'
payload = '''

G.GAME.unik_blindside_reroll_tags_consumed = G.GAME.unik_blindside_reroll_tags_consumed or 0
print("reroll tags consumed:" .. G.GAME.unik_blindside_reroll_tags_consumed)
SMODS.change_free_rerolls(-G.GAME.unik_blindside_reroll_tags_consumed)
G.GAME.unik_blindside_reroll_tags_consumed = 0
print("Free rerolls remaining:" .. G.GAME.round_resets.free_rerolls)

'''

##blindside: doubled up jokers may appear anytime after you win!

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "items/jokers/smalljokers.lua"]'
pattern = '''return G.GAME.modifiers.enable_bld_elites and G.GAME.round_resets.ante == 3'''
match_indent = true
position = 'at'
payload = '''
return (G.GAME.modifiers.enable_bld_elites and G.GAME.round_resets.ante == 3) or G.GAME.round_resets.ante > 7
'''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "items/jokers/bigjokers.lua"]'
pattern = '''return G.GAME.modifiers.enable_bld_elites and G.GAME.round_resets.ante == 5'''
match_indent = true
position = 'at'
payload = '''
return (G.GAME.modifiers.enable_bld_elites and G.GAME.round_resets.ante == 5) or G.GAME.round_resets.ante > 7
'''

###blindside: gros/cavendish always spawns in starting ante

[[patches]]
[patches.regex]
target = '=[SMODS Blindside "items/jokers/bigjokers.lua"]'
pattern = '''G\.GAME\.round\_resets\.ante \~\= 1'''
match_indent = true
position = 'at'
payload = ''' G.GAME.unik_banana_generated '''

[[patches]]
[patches.regex]
target = '=[SMODS Blindside "items/jokers/bigjokers.lua"]'
pattern = '''G\.GAME\.round\_resets\.ante \=\= 1'''
match_indent = true
position = 'at'
payload = ''' not G.GAME.unik_banana_generated '''

[[patches]]
[patches.regex]
target = '=[SMODS Blindside "items/jokers/smalljokers.lua"]'
pattern = '''G\.GAME\.round\_resets\.ante \=\= 1'''
match_indent = true
position = 'at'
payload = ''' not G.GAME.unik_banana_generated '''


[[patches]]
[patches.regex]
target = '=[SMODS Blindside "items/jokers/smalljokers.lua"]'
pattern = '''G\.GAME\.round\_resets\.ante \~\= 1'''
match_indent = true
position = 'at'
payload = ''' G.GAME.unik_banana_generated '''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "lib/utils/uishop.lua"]'
pattern = '''card:set_edition(edition, true)'''
match_indent = true
position = 'before'
payload = '''
edition = UNIK.add_detrimental_edition_blindside(edition)
'''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "lib/utils/uishop.lua"]'
pattern = '''card:set_edition(edition, true)'''
match_indent = true
position = 'after'
payload = '''
if isDetrimentalEdition2(edition) then
card.cost = card.cost - 2
end
'''

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''if _tag.key == 'tag_bld_reroll' then
    SMODS.change_free_rerolls(1)
end'''
match_indent = true
position = 'at'
payload = '''
--overridden, will use hook instead
'''