[manifest]
version = "0.0.1"
dump_lua = true
priority = 99999

[[patches]]
[patches.regex]
target = '=[SMODS Blindside "lib/utils/utils.lua"]'
pattern = '''(.*)function BLINDSIDE.chipsupdate(.*)'''
match_indent = true
position = 'after'
payload = '''

G.GAME.unik_current_operator = G.GAME.unik_current_operator or 0

'''

[[patches]]
[patches.regex]
target = '=[SMODS Blindside "lib/utils/utils.lua"]'
pattern = '''G.GAME.blind.basechips\*G.GAME.blind.mult'''
match_indent = true
position = 'at'
payload = ''' UNIK.arrowfunction(G.GAME.unik_current_operator,G.GAME.blind.basechips,G.GAME.blind.mult) '''

[[patches]]
[patches.regex]
target = '=[SMODS _ "src/ui.lua"]'
pattern = '''text = \"X\"'''
match_indent = true
position = 'after'
payload = ''', id = "unik_operator_text_7777" '''

# the trench reset
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''
-- TARGET: effects after end of round evaluation
'''
match_indent = true
position = 'after'
payload = '''
if BLINDSIDE then
    for i, card in pairs(G.playing_cards) do
        if card.ability and card.ability.extra and card.ability.extra.e_chips and card.config.center.key == 'm_unik_blindside_epic_trench' then
            card.ability.extra.e_chips = card.ability.extra.e_chips_base
        end
        card.ability.unik_burned_by_hook = nil
    end
end
'''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "lib/utils/utils.lua"]'
pattern = '''-- TARGET: card destroyed'''
match_indent = true
position = 'after'
payload = '''

'''
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''table.insert(cards, _cards[i])'''
match_indent = true
position = 'after'
payload = '''
if _cards[i].unik_burned_by_hook then
    _cards[i].unik_burned_by_hook = nil
    burned = true
end
'''

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''table.insert(cards, _retained_cards[i])'''
match_indent = true
position = 'after'
payload = '''
if _retained_cards[i].unik_burned_by_hook then
    _retained_cards[i].unik_burned_by_hook = nil
    burned = true
end
'''

[[patches]]
[patches.regex]
target = 'functions/state_events.lua'
pattern = '''SMODS.calculate_context\(\{(.*)end_of_round = true(.*)game_over = game_over(.*)'''
match_indent = true
position = 'after'
payload = '''

G.GAME.last_joker = G.GAME.blind.boss

'''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "lib/utils/uishop.lua"]'
pattern = '''for i = 1, #G.GAME.tags do
                                    G.GAME.tags[i]:apply_to_run({type = 'shop_start'})
                                end'''
match_indent = true
position = 'before'
payload = '''
--on loading a save, prevent tags from being consumed as if entering the shop.
if not G.GAME.shop_entered_already_blindside then
G.GAME.shop_entered_already_blindside = true
'''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "lib/utils/uishop.lua"]'
pattern = '''for i = 1, #G.GAME.tags do
                                    G.GAME.tags[i]:apply_to_run({type = 'shop_start'})
                                end'''
match_indent = true
position = 'after'
payload = '''
end
'''

[[patches]]
[patches.regex]
target = 'functions/button_callbacks.lua'
pattern = '''(.*)SMODS.calculate_context\(\{(.*)ending_shop = true(.*)\}\)(.*)'''
match_indent = true
position = 'after'
payload = '''

G.GAME.unik_blindside_reroll_tags_consumed = G.GAME.unik_blindside_reroll_tags_consumed or 0
print("reroll tags consumed:" .. G.GAME.unik_blindside_reroll_tags_consumed)
SMODS.change_free_rerolls(-G.GAME.unik_blindside_reroll_tags_consumed)
G.GAME.unik_blindside_reroll_tags_consumed = 0
print("Free rerolls remaining:" .. G.GAME.round_resets.free_rerolls)
G.GAME.shop_entered_already_blindside = nil

'''

##blindside: doubled up jokers may appear anytime after you win!

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "items/jokers/smalljokers.lua"]'
pattern = '''return G.GAME.modifiers.enable_bld_elites and G.GAME.round_resets.ante == 3'''
match_indent = true
position = 'at'
payload = '''
return (G.GAME.modifiers.enable_bld_elites and G.GAME.round_resets.ante == 3) or G.GAME.round_resets.ante > 7
'''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "items/jokers/bigjokers.lua"]'
pattern = '''return G.GAME.modifiers.enable_bld_elites and G.GAME.round_resets.ante == 5'''
match_indent = true
position = 'at'
payload = '''
return (G.GAME.modifiers.enable_bld_elites and G.GAME.round_resets.ante == 5) or G.GAME.round_resets.ante > 7
'''

###blindside: gros/cavendish always spawns in starting ante

[[patches]]
[patches.regex]
target = '=[SMODS Blindside "items/jokers/bigjokers.lua"]'
pattern = '''G\.GAME\.round\_resets\.ante \~\= 1'''
match_indent = true
position = 'at'
payload = ''' G.GAME.unik_banana_generated '''

[[patches]]
[patches.regex]
target = '=[SMODS Blindside "items/jokers/bigjokers.lua"]'
pattern = '''G\.GAME\.round\_resets\.ante \=\= 1'''
match_indent = true
position = 'at'
payload = ''' not G.GAME.unik_banana_generated '''

[[patches]]
[patches.regex]
target = '=[SMODS Blindside "items/jokers/smalljokers.lua"]'
pattern = '''G\.GAME\.round\_resets\.ante \=\= 1'''
match_indent = true
position = 'at'
payload = ''' not G.GAME.unik_banana_generated '''


[[patches]]
[patches.regex]
target = '=[SMODS Blindside "items/jokers/smalljokers.lua"]'
pattern = '''G\.GAME\.round\_resets\.ante \~\= 1'''
match_indent = true
position = 'at'
payload = ''' G.GAME.unik_banana_generated '''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "lib/utils/uishop.lua"]'
pattern = '''card:set_edition(edition, true)'''
match_indent = true
position = 'before'
payload = '''
edition = UNIK.add_detrimental_edition_blindside(edition)
'''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "lib/utils/uishop.lua"]'
pattern = '''card:set_edition(edition, true)'''
match_indent = true
position = 'after'
payload = '''
if isDetrimentalEdition2(edition) then
card.cost = card.cost - 2
end
'''

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''if _tag.key == 'tag_bld_reroll' then
    SMODS.change_free_rerolls(1)
end'''
match_indent = true
position = 'at'
payload = '''
--overridden, will use hook instead
'''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "lib/utils/hands.lua"]'
pattern = '''-- begin iteration from first (not already considered) card'''
match_indent = true
position = 'after'
payload = '''
--print(colorsuits)
'''


[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "lib/utils/hands.lua"]'
pattern = '''-- < 5 hand cant be a spectrum'''
match_indent = true
position = 'after'
payload = '''
--print("Hand size:" .. #hand)
'''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "lib/utils/hands.lua"]'
pattern = '''-- if somehow no suits: spectrum is impossible'''
match_indent = true
position = 'after'
payload = '''
--print("cardcolors:" .. #cardcolors)
'''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "lib/utils/hands.lua"]'
pattern = '''if colorsuits[cardcolors[1]] == false then return {} end'''
match_indent = true
position = 'after'
payload = '''
--SORRY, but stuff can HAVE SPECTRUMS INSIDE (goob eval, playing 6 cards)
'''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "items/jokers/showdownjokers.lua"]'
pattern = '''if value.config.center and value.config.center.config.extra and value.config.center.config.extra.stubborn then'''
match_indent = true
position = 'at'
payload = '''
if value.ability and value.ability.extra and type(value.ability.extra) == 'table' and value.ability.extra.stubborn and value.config.center.config.extra.stubborn then
'''

[[patches]]
[patches.regex]
target = '=[SMODS Blindside "lib/utils/utils.lua"]'
pattern = '''G\.GAME\.blind\.mult \+ mult'''
match_indent = true
position = 'at'
payload = '''math.max(1,to_big(G.GAME.blind.mult + mult))'''


[[patches]]
[patches.regex]
target = '=[SMODS Blindside "lib/utils/utils.lua"]'
pattern = '''G\.GAME\.blind\.mult\*xmult'''
match_indent = true
position = 'at'
payload = '''math.max(1,to_big(G.GAME.blind.mult*xmult))'''

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''if v.small or v.big then bosses_used[k] = 0 end'''
match_indent = true
position = 'after'
payload = '''
if v.cursed then bosses_used[k] = 0 end
'''
### Also, it appears blinds remaining face down even after they are played are not intentional, given a lot of chance effects only trigger if they are NOT face down.
###I'll have to fix that
### stuff like the wheel never trigger for that reason without changes

# pareidolia perkeo fix
[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = '''stay_flipped = G.GAME and G.GAME.blindassist and G.GAME.blindassist:stay_flipped(to, card, from)'''
match_indent = true
position = 'at'
payload = '''stay_flipped = G.GAME and G.GAME.blindassist and G.GAME.blindassist:stay_flipped(to, card, area)'''


# pareidolia perkeo fix
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''check_for_unlock({type = 'run_card_replays'})'''
match_indent = true
position = 'before'
payload = '''
if UNIK.hasBlindside() then
    for i = 1, #G.hand.highlighted do
        if G.hand.highlighted[i].facing == 'back' then
            G.hand.highlighted[i]:flip()
            
        end
    end
end
'''

### localization change whenever blindside is active

[[patches]]
[patches.regex]
target = 'functions/UI_definitions.lua'
pattern = '''\'ph\_choose\_blind\_2\''''
match_indent = true
position = 'after'
payload = '''.. (UNIK.hasBlindside() and '_blindside' or "")'''

[[patches]]
[patches.regex]
target = 'functions/UI_definitions.lua'
pattern = '''\'ph_up_ante_2\''''
match_indent = true
position = 'after'
payload = '''.. (UNIK.hasBlindside() and '_blindside' or "")'''

[[patches]]
[patches.regex]
target = 'functions/UI_definitions.lua'
pattern = '''\'ph_up_ante_3\''''
match_indent = true
position = 'after'
payload = '''.. (UNIK.hasBlindside() and '_blindside' or "")'''

[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "lib/utils/ui.lua"]'
pattern = '''if G.GAME and G.GAME.selected_back.effect.center.config.extra and G.GAME.selected_back.effect.center.config.extra.blindside then'''
match_indent = true
position = 'at'
payload = '''if UNIK.hasBlindside() then'''

###FIX YOUR MOD!!!!!!
[[patches]]
[patches.pattern]
target = '=[SMODS Blindside "lib/utils/ui.lua"]'
pattern = '''return run_info_ref'''
match_indent = true
position = 'at'
payload = '''
local ret = run_info_ref()
return ret
'''

