[manifest]
version = "0.0.1"
dump_lua = true
priority = 9999

### display the fake score before not allowing the hand and/or adding to blind, now with bunco compat.
[[patches]]
[patches.regex]
target = 'functions/state_events.lua'
pattern = '''SMODS\.calculate\_main\_scoring\((.*)\)'''
position = 'after'
payload = '''

----------NEW------------------------

'''