[manifest]
version = "0.0.1"
dump_lua = true
priority = 214748365

[[patches]]
[patches.pattern]
target = '''=[SMODS JokerDisplay "src/api_helper_functions.lua"]'''
pattern = '''polychrome = { atlas = "cry_atlaseditiondeck", pos = { x = 2, y = 0 } },'''
position = "after"
payload = '''
unik_positive = { atlas = "unik_decks", pos = { x = 3, y = 0 } },
unik_bloated = { atlas = "unik_decks", pos = { x = 4, y = 0 } },
unik_halfjoker = { atlas = "unik_decks", pos = { x = 5, y = 0 } },
unik_fuzzy = { atlas = "unik_decks", pos = { x = 3, y = 1 } },
unik_corrupted = { atlas = "unik_decks", pos = { x = 4, y = 1 } },
unik_steel = { atlas = "unik_decks", pos = { x = 5, y = 1 } },
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS JokerDisplay "definitions/display_definitions.lua"]'''
pattern = '''j_ramen = { -- Ramen
        text = {
            {
                border_nodes = {
                    { text = "X" },
                    { ref_table = "card.ability", ref_value = "x_mult", retrigger_type = "exp" }
                }
            }
        }
    },'''
position = "at"
payload = '''
j_ramen = { -- Ramen
        text = {
            {
                border_nodes = {
                    { text = "X" },
                    { ref_table = "card.ability.extra", ref_value = "Xmult", retrigger_type = "exp" }
                }
            }
        }
    },
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS JokerDisplay "definitions/display_definitions.lua"]'''
pattern = '''j_popcorn = { -- Popcorn
        text = {
            { text = "+" },
            { ref_table = "card.ability", ref_value = "mult", retrigger_type = "mult" }
        },
        text_config = { colour = G.C.MULT },
    },'''
position = "at"
payload = '''j_popcorn = { -- Popcorn
        text = {
            { text = "+" },
            { ref_table = "card.ability.extra", ref_value = "mult", retrigger_type = "mult" }
        },
        text_config = { colour = G.C.MULT },
    },
'''
match_indent = true