[manifest]
version = "0.0.1"
dump_lua = true
priority = 214748365

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = '''if not hidden_suits[visible_suit[i]] then'''
position = "at"
payload = '''if visible_suit[i] and not hidden_suits[visible_suit[i]] then'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''functions/common_events.lua'''
pattern = '''SMODS.upgrade_poker_hands({'''
position = "after"
payload = '''
instant = instant,
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_objects/runselectpage.lua"]'''
pattern = '''if card.config.center.shiny then Sprite.draw_shader(_sprite, 'negative_shine', nil, _sprite.ARGS.send_to_shader) end'''
position = "after"
payload = '''
if card.config.center.unik_shader then Sprite.draw_shader(_sprite, card.config.center.unik_shader, nil, _sprite.ARGS.send_to_shader) end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_objects/runselectpage.lua"]'''
pattern = '''if card.config.center.shiny then Sprite.draw_shader(_sprite, 'voucher', nil, _sprite.ARGS.send_to_shader) end'''
position = "after"
payload = '''
if card.config.center.unik_shader then Sprite.draw_shader(_sprite, card.config.center.unik_shader, nil, _sprite.ARGS.send_to_shader) end
'''
match_indent = true